# Generated by Django 3.1.13 on 2021-08-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthScopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('FB', 'Facebook'), ('GH', 'GitHub'), ('TW', 'Twitter'), ('GL', 'Google')], max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
