# Generated by Django 3.1.13 on 2021-08-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210822_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars'),
        ),
    ]
